# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    allowed_methods_listener: true
#    routing_loader: true
    view:
        view_response_listener: true
        failed_validation: 422
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    disable_csrf_role: ROLE_API
