version: '3.8'

services:
    mysql:
        image: mysql:8.0
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - './:/usr/src/app'
        ports:
            - '${MYSQL_PORT}:3306'
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
            - .env
            - .env.local
        user: ${LOCAL_USER}
        volumes:
            # делаем ссылку с теущей папки на папку /usr/src/app в докере, чтобы не пересобирать контейнер при изменениях в коде
            - .:/usr/src/app
        networks:
            - app-network

    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        depends_on:
            - php
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
